name: Swift

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-format:
    name: Check source code formatting
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check formatting
        run: |
            swift format --in-place --recursive Sources Tests
            if test -n "$(git ls-files -m)"; then
              echo 'Some files were not properly formatted, please run `swift format --in-place --recursive Sources Tests`'
              git status
              exit 1;
            fi
  build-doc:
    name: Build documentation
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build documentation
        run: |
            swift package --allow-writing-to-directory docs \
                 generate-documentation \
                 --target Biscuits \
                 --disable-indexing \
                 --transform-for-static-hosting \
                 --output-path docs
  build:
    name: Build and test on ${{ matrix.os }}
    strategy:
      matrix:
        # TODO re-enable ubuntu-latest
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
